### ISSUE TITLE
FC frozen after add  timer b00 1 timer b01 1

### ISSUE THREAD

**Issue by RadomirJ** [betaflight/bidircfg#1]

**Comment by RadomirJ** [comment]
Motors 1 and 2 doesn't work with dshot bidir, after fix timer settings fc completely frozen. I used clracing f4.

**Comment by joelucid** [comment]
Try the update snippet. It works now.

**Comment by mikeller** [comment]
@RadomirJ: Please provide the information that you were asked to provide when opening an issue. Otherwise nobody is going to be able to help you.

**Comment by RadomirJ** [comment]
I tried run snippet but motors 1 and 2 still does not spin.

**Comment by cudakeer808** [comment]
@RadomirJ , copy the four lines for the timers first then paste it on CLI. Press enter. Do not save YET. Then copy the four lines for dma, paste it in CLI then press enter. Only then you can paste the rest of the snippet.

copy and paste timers. enter. copy and paste dmas. enter. only then paste everything else. enter. save.

**Comment by SebiWolze** [comment]
Set up BF 4.0 from scratch
set beeper_frequency = 0
paste snippet into CLI
