### ISSUE TITLE
Bidirectional Dshot Piro F4 doesn't work with LED's enabled

### ISSUE THREAD

**Issue by Yamaford** [betaflight/bidircfg#18]
Motor 2 ((motor 01 in cli) doesn't give RPM on the Dshot_telemetry_info command in CLI. I'n Blheli32 it gives 155 bad info packets on motor 2. Disable LED's and everything works great. 
Fujin hinted there may be a workaround if I didn't need Camera control but I don't even know enough to be dangerous. 
Any suggestions?
DEF_TIM(TIM11, CH1,  PB9, TIM_USE_CAMERA_CONTROL, 0, 0), // CAMERA_CONTROL_PIN

DEF_TIM(TIM3,  CH4,  PB1, TIM_USE_MOTOR,           0, 0),  // M1_OUT - D1_ST2_CH5

DEF_TIM(TIM8,  CH2N, PB0, TIM_USE_MOTOR,           0, 0),  // M2_OUT - D2_ST3_CH7

DEF_TIM(TIM8,  CH4,  PC9, TIM_USE_MOTOR,           0, 0),  // M3_OUT - D2_ST7_CH7

DEF_TIM(TIM1,  CH1,  PA8, TIM_USE_MOTOR,           0, 1),  // M4_OUT - D2_ST1_CH6

DEF_TIM(TIM4,  CH3,  PB8, TIM_USE_LED ,            0,  0)    // LED & MOTOR5 D1_ST7_CH2

**Comment by joelucid** [comment]
This problem can't be resolved. You have to use dshot bitbang in this case.
