### ISSUE TITLE
Bidirectional DSHOT: KAKUTEF7 & Tekko32 Dshot invalid pkts at 90-100% but osd shows esc RPM

### ISSUE THREAD

**Issue by avrahams** [betaflight/bidircfg#22]
I am trying to enable Bidirectional DSHOT on KAKUTEF7 with Tekko32 
I upgrade the esc firmware and used the default config snippet
but in the cli I see that almost all Dshot packages are invalid

I do see the ESC telemetry is the osd  (RPM, Temp, current etc) so I guess that the problem is not with my esc

**Comment by ghost** [comment]
I just enabled using the latest blheli hex, nightly builds, and following the default snippet:

just sitting, quad is off.. seems to alternate between diff motors.

# dshot_telemetry_info
Dshot reads: 3072690
Dshot invalid pkts: 336882
Dshot irq micros: 3

Motor     RPM   Invalid
=====   =====   =======
    0       0    12.19%
    1       0     0.00%
    2    2047    19.59%
    3       0     9.51%

9 8 15 10 18 12 0 14 2 17 4 19 7 1 9 3 11 6 13 8 16 10 18 12 0 15 10 17 12 19 15 1 
19 15 14 14 15 15 14 14 15 15 14 14 15 7 7 6
