### ISSUE TITLE
LED Conflict RPM filter

### ISSUE THREAD

**Issue by Gaz-B** [betaflight/bidircfg#27]
This seems very odd but if I have LEDs enabled with RPM filter LEDs don't work and motors spin for a fraction of a second then shut off with LEDs switched of in the configurator motors work fine. This isn't a new build LEDs function is fine up until I add the RPM Filter changes. This is operating motors from Betaflight or BL-32 configurators. Pyrodrone F4 and Typhoon v2.? 4 in 1. full release 4.0 and BL32.6.8.

**Comment by joelucid** [comment]
This issue is solved by dshot bitbang. It's what we developed Bitbang for.
