### ISSUE TITLE
problems with mamba f722 mini (packet loss and no current sensing) 

### ISSUE THREAD

**Issue by m013** [betaflight/bidircfg#32]
tried 4.0.4 and 4.1 #1746
blheli versions Rev32.6.4 and Rev32.6.5 respectively

the first problem - huge packet loss (up to 40%) i cant even arm (rpmfilter warning).
with Rev32.6.5 two of the motors get no data

the second - although i have telemetry readings from the esc on osd (rpm and temperature), i have no current sensing. i know you have to apply some load on motors tjo get readings, but i did it via motor test tab and still nothing. note that there is no current calibration setting in blheli suite
[dump.txt](https://github.com/betaflight/betaflight/files/3389729/dump.txt)
![curr](https://user-images.githubusercontent.com/37451707/61182522-2118cc80-a63d-11e9-8dbc-751f9be93034.PNG)
![settings](https://user-images.githubusercontent.com/37451707/61182523-2118cc80-a63d-11e9-9265-063dc81b9e97.PNG)

**Comment by jorgemiar** [comment]
@m013 were you able to get the current sensor working? I've set the current to Onboard ADC (as I'm using the current cable from ESC) but getting 0V when plugging the battery.

**Comment by m013** [comment]
> 
> 
> @m013 were you able to get the current sensor working? I've set the current to Onboard ADC (as I'm using the current cable from ESC) but getting 0V when plugging the battery.
have you tried to fly ?maybe it doesnt output small currents

**Comment by jorgemiar** [comment]
@m013 But I'm not even getting a voltage reading, everything is at 0.

**Comment by m013** [comment]
@jorgemia  i had no problems with voltage back then
