### ISSUE TITLE
Add MATEKF411RX to Bidirectional DSHOT and RPM Filter supported target

### ISSUE THREAD

**Issue by emski0** [betaflight/bidircfg#36]
Hi
I just want to mention that i tried Bidirectional DSHOT and RPM Filter on MATEKF411RX(tinyhawk s) and it works with the default snippets. I used  it with the BLHeli_S JESC from https://jflight.net/.
So maybe you can MATEKF411RX with default snippets to the supported targets.

**Comment by mikeller** [comment]
I can confirm that - gave it a spin on a CRAZYBEEF4FR which is essentially a MATEKF411RX, and it works like a charm.

**Comment by joelucid** [comment]
Added to rpm wiki page together with MATEKF411 and MAMBAF411 which all show no conflicts for dma and timers.
