### ISSUE TITLE
Matek F411: BF 4.1 DShot BitBang not working when assigning Pin A08 (LED) to cam control

### ISSUE THREAD

**Issue by RipperDrone** [betaflight/bidircfg#40]
BetaFPV Whoop AIO 2-4S with Matek F411 FC, BF 4.1: 
BF 4.1 DShot BitBang not working when assigning Pin A08 (LED) to cam control

- flash BF 4.1 Nightly (today's first)
- flash JESC, rpm telemetry (v2.1, 24kHz version) to ESCs
- paste universal snippet to enable rpm telemetry and DSHOT300 etc. (from BF 4.1)
- CLI this:
# resource LED_STRIP 1 NONE
# resource CAMERA_CONTROL 1 A08

Everything worked ok until I remapped the LED_STRIP pin. Seems timers are used differently now, because it did work in non bit bang mode before.

**Comment by joelucid** [comment]
@RipperDrone could you verify whether this is fixed now that #8978 has been merged?

**Comment by RipperDrone** [comment]
@joelucid confirmed, it's fixed. Verified on RacerX Twig, Matek F411, 
![image](https://user-images.githubusercontent.com/12601105/66945387-460f4800-f04f-11e9-9063-f73e9e145156.png)

--> running on JESC, smooth as silk :-)

**Comment by joelucid** [comment]
Perfect, thanks for testing!
